# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Client' do
	pod 'SocketRocket'
    pod 'CocoaAsyncSocket'
    pod 'CocoaLumberjack'
end

target 'ServerOSX' do
    pod 'CocoaAsyncSocket'
    pod 'CocoaLumberjack'
end
